services:
  - type: web
    name: sehatai-ml-server
    env: python
    region: frankfurt
    plan: starter # Needs at least Starter (512MB RAM) to load 4 PyTorch models
    rootDir: ml_server
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
